---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-dep
  labels:
    app: react-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
        - name: react-nginx
          image: arturix/react-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-nginx-ext-svc
spec:
  selector:
    app: react-nginx
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      protocol: TCP
